title = "Rjac"  # From Git
gitRepoUrl = "https://github.com/Giant427/Rjac" # From Git

gitSourceBranch = "main"

[footer]
style = "dark"
copyright = "Copyright © 2021 Giant427. Built with Moonwave and Docusaurus"